# Generated by Django 2.2.16 on 2020-09-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcription_period', models.IntegerField(default=3)),
                ('savings', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('no_of_biodata', models.IntegerField()),
                ('no_of_emp_e_doc', models.IntegerField()),
                ('no_of_subaccount', models.IntegerField()),
                ('no_of_subdomain_website', models.IntegerField(default=1)),
                ('no_sales_enquiries', models.CharField(blank=True, max_length=20)),
                ('color_scheme', models.CharField(max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subplans.PlanTitle')),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subplans.PlanType')),
            ],
        ),
    ]
