# Generated by Django 2.2.16 on 2020-09-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantitle',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
