# Generated by Django 2.2.16 on 2020-09-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplans', '0002_auto_20200902_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
