# Generated by Django 2.2.16 on 2020-09-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subplans', '0003_auto_20200902_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plandetail',
            old_name='subcription_period',
            new_name='subscription_period',
        ),
    ]
