# Generated by Django 2.2.16 on 2020-09-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplans', '0004_auto_20200903_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='no_of_biodata',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='no_of_emp_e_doc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
