# Generated by Django 2.2.16 on 2020-09-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subplans', '0006_plandetail_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandetail',
            name='popularity',
        ),
    ]
