# Generated by Django 2.2.16 on 2020-09-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subplans', '0007_remove_plandetail_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='no_of_subdomain_website',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
